
trigger: none

pool: default

stages:
  - stage: terraforminit
    jobs:
      - job: jaob1
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'todo-svc'
            backendAzureRmResourceGroupName: 'ramu-rg'
            backendAzureRmStorageAccountName: 'todostg'
            backendAzureRmContainerName: 'patelcont'
            backendAzureRmKey: 'key-tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)env/dev'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            environmentServiceNameAzureRM: 'todo-svc'
      - job: jaob2
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'todo-svc'
            backendAzureRmResourceGroupName: 'ramu-rg'
            backendAzureRmStorageAccountName: 'todostg'
            backendAzureRmContainerName: 'patelcont'
            backendAzureRmKey: 'key-tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'todo-svc'